nodeLinker: node-modules

# Core settings
yarnPath: .yarn/releases/yarn-4.8.1.cjs  # Match your Yarn version
enableGlobalCache: true  # Better caching
enableMirror: true       # Faster downloads

# Optional but recommended for CI
checksumBehavior: "throw"  # Strict dependency validation